[package]
name = "internet_test"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tic"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
